### ISSUE TITLE
[feature request] Better readability for long / multiple branch names

### ISSUE THREAD

**Issue by lheinold** [phil294/GitLG#103]
The current behavior of multiple long branch names on the same commit looks like this:

<img width="950" alt="Screenshot 2024-09-05 at 1 28 41 PM" src="https://github.com/user-attachments/assets/e3d023b4-449d-4e8b-bd24-ff2fc05fc808">

This is quite hard to read and it can be hard to tell if there are additional branches at that commit unless you click on it. Branch names also tend to continue past the end of the page.

I think it would be more readable if the branch names were truncated and/or had a label for "x more branches", like this:

<img width="879" alt="Screenshot 2024-09-05 at 1 22 01 PM" src="https://github.com/user-attachments/assets/4e4c7f17-3158-4e82-b238-c0c30453aace">
<img width="879" alt="Screenshot 2024-09-05 at 1 21 09 PM" src="https://github.com/user-attachments/assets/fd1a3478-59ba-411b-9ed5-ecd25d950085">

Another option could be some kind of horizontal scrolling for branch names, but I have no idea how easy that is to add. Horizontal scroll might also interfere with the "hover to see commit message" feature (which is very useful).

**Comment by webJose** [comment]
Suggestion:  Limit the width of branches to a maximum.  On hover or focus, the whole name is presented.

**Comment by lheinold** [comment]
Do you mean this config option? 
`    "git-log--graph.branch-width": 3,`
Or a different one?

I tried a bunch of different values (2,3,5,7,10) and while it did change the display (the width between lines on the left changed), it didn't appear to affect the branch names themselves. Long names still keep going past the end of the screen.

**Comment by phil294** [comment]
I think webjose meant the branch names, for which there hasn't been a max width so far.

I've added an option (default active) to combine remotes + local branch into one, and set the max width of branch/ref tips names to 350px. If it exceeds that, you can then hover the branch name to see it in its entirety or hover the branch lines to see the full commit message. Also the ref tips are now placed at the beginning of the subject lines:

![image](https://github.com/user-attachments/assets/44885550-8365-4ba7-816c-3463291c03ac)

This is still the sanest place to put them imo. These changes very much reflect the way the interface is set up in the other Git Graph extension as well.

I'm happy with how it behaves now, but maybe I'm missing some use cases, so if you think otherwise, please let me know.

**Comment by phil294** [comment]
horizontal scrolling would be pretty anti-ergonomic imo, things should be visible without much user interaction.

the "X more branches..." is nice but very complicated to do because you'd need to calculate the bubbles' width with JS and so on.
