### ISSUE TITLE
Internal: Code formatter

### ISSUE THREAD

**Issue by lens0021** [phil294/GitLG#24]
There are trailing whitespaces and my vscode complained about it.

**Comment by phil294** [comment]
Are you using some kind of extension that warns you about it? I wanna use it too.

It's probably not possible to apply semantic language-agnostic code formatting due to the amount of preprocessors: Vue/SLM/Coffee/Stylus. For example, there's coffeelint but it doesn't work in Vue files. So all that could be done is integrating some generic language-indifferent checker which I'd then integrate in the build script `release.sh`. The whole process is still pretty manual, after all.

**Comment by lens0021** [comment]
What I am using is not an extension but VSCode's `files.trimTrailingWhitespace` setting.

> When enabled, will trim trailing whitespace when saving a file.

But, if you prefer, pre-commit could help you by [the `trailing-whitespace` hook](https://github.com/pre-commit/pre-commit-hooks#trailing-whitespace) I think. Anyway, I didn't know the limitation you mentioned, sorry.

**Comment by phil294** [comment]
This has become obsolete since the removal of coffeescript etc and the addition of eslint which does indeed enforce a unified code style
